server {
    listen ${PORT} default_server;
    server_name _;

    root /app/public;
    index index.php index.html;

    charset utf-8;

    # Logs sent to stdout/stderr so they show up in Railway dashboard
    access_log /dev/stdout;
    error_log /dev/stderr;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM Proxy
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        
        # Optimization
        fastcgi_connect_timeout 60;
        fastcgi_send_timeout 60;
        fastcgi_read_timeout 60;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }

    location ~* \.(jpg|jpeg|png|gif|css|js|ico|svg|woff|woff2|ttf|txt)$ {
        try_files $uri =404;
        access_log off;
        expires 7d;
    }

    # Deny access to .htaccess or hidden files
    location ~ /\. {
        deny all;
    }
}