server {

    listen ${PORT};

    server_name _;

    root /app/public;

    index index.php index.html;

    access_log /dev/stdout;
    error_log /dev/stderr;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {

        include fastcgi_params;

        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_pass 127.0.0.1:9001;

        fastcgi_connect_timeout 60;
        fastcgi_send_timeout 60;
        fastcgi_read_timeout 60;

    }

    location ~* \.(jpg|jpeg|png|gif|css|js|ico|svg|woff|woff2|ttf|txt)$ {

        try_files $uri =404;

        access_log off;

        expires 7d;

    }

}